name = "Ghostium"
license = "MIT"
licenselink = "http://sm.mit-license.org/"
description = "Yet another port of oswaldoacauan's ghostium theme to Hugo"
homepage = "https://github.com/kpavlov/hugo-theme-ghostium"
tags = ["blog", "ghostium", "highlightjs", "pjax"]
features = ["blog"]
min_version = 0.14

[author]
  name = "Konstantin Pavlov"
  homepage = "https://github.com/kpavlov/hugo-theme-ghostium"

# If porting an existing theme
[original]
  name = "oswaldoacauan"
  homepage = "https://github.com/oswaldoacauan/ghostium"
  repo = "https://github.com/oswaldoacauan/ghostium"
